import { Gauge, Pause, Play, Plus, RotateCcw, SkipForward, Zap } from 'lucide-react'
import { useSimulationStore } from '../../stores/useSimulationStore'
import type { DispatchStrategy } from '../../simulation/models/types'

export function SimulationControls({ compact = false }: { compact?: boolean }): React.JSX.Element {
  const simulation = useSimulationStore((store) => store.simulation); const toggle = useSimulationStore((store) => store.toggleRunning); const step = useSimulationStore((store) => store.step); const reset = useSimulationStore((store) => store.reset)
  const addLot = useSimulationStore((store) => store.addLot); const strategy = useSimulationStore((store) => store.strategy); const speed = useSimulationStore((store) => store.speed); const setSpeed = useSimulationStore((store) => store.setSpeed); const nextDemo = useSimulationStore((store) => store.nextDemo)
  if (compact) return <div className="control-row"><button className="btn primary" onClick={toggle}>{simulation.running ? <Pause size={13} /> : <Play size={13} />}{simulation.running ? 'Pause' : 'Run'}</button><button className="btn" onClick={nextDemo}><SkipForward size={13} /> Next demo event</button><select className="select" aria-label="Simulation speed" value={speed} onChange={(event) => setSpeed(Number(event.target.value))}>{[.5,1,2,5,10].map((value) => <option key={value} value={value}>{value}×</option>)}</select></div>
  return <div className="panel controls-print-hide"><div className="panel-header"><h3>Scenario control</h3><span className="tiny muted mono">T+{simulation.time.toFixed(1)}s</span></div><div className="panel-body">
    <div className="control-row"><button className="btn primary" onClick={toggle}>{simulation.running ? <Pause size={13} /> : <Play size={13} />}{simulation.running ? 'Pause' : simulation.time > 0 ? 'Resume' : 'Start'}</button><button className="btn" onClick={() => step(1)} disabled={simulation.running}><SkipForward size={13} />Step</button><button className="btn" onClick={reset}><RotateCcw size={13} />Reset</button></div>
    <div className="divider" /><div className="control-row"><button className="btn" onClick={() => addLot(false)}><Plus size={13} />Lot</button><button className="btn" onClick={() => addLot(true)}><Zap size={13} />Urgent</button><button className="btn active" onClick={nextDemo}><SkipForward size={13} />Next demo event</button></div>
    <div className="divider" /><div className="field-row"><div className="field"><label>Dispatch strategy</label><select className="select" value={simulation.config.strategy} onChange={(event) => strategy(event.target.value as DispatchStrategy)}><option value="fifo">FIFO</option><option value="nearest">Nearest vehicle</option><option value="priority">Priority-aware</option><option value="bottleneck">Bottleneck-aware</option></select></div><div className="field"><label><Gauge size={10} /> Simulation speed</label><select className="select" value={speed} onChange={(event) => setSpeed(Number(event.target.value))}>{[.5,1,2,5,10].map((value) => <option key={value} value={value}>{value}×</option>)}</select></div></div>
  </div></div>
}
